#server.port=0
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/ ,
#http://${eureka.instance.hostname}:8761/eureka/


server:
  port: 0
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ ,
#                   http://${eureka.instance.hostname}:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ToryXu0407/configServer.git
