#server.port=0
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:8761/eureka/ ,
#http://${eureka.instance.hostname}:8761/eureka/


server:
  port: 0
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/ ,
#                   http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: dev
  cloud:
    config:
      uri: http://localhost:8080
